### ISSUE TITLE
Drop CakePHP 2.x support in favor of 3.x

### ISSUE THREAD

**Issue by egeloen** [egeloen/ivory-http-adapter#101]
This issue is here for getting feedback about something I would like to drop. Basically, CakePHP 3.x has been released with namespace support. I would like to migrate the current adapter to this new version but I wouldn't want to maintain two adapters for both versions.

So, is anyone agree about dropping the CakePHP 2.x support in favor of the 3.x one?

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by jeromegamez** [comment]
:+1: from me as well. The Adapter is in a 0.x state, and the previous versions work well - if someone needs it, they can stick with a previous release. (The same reason would apply to the Guzzle 3.x support, btw :)

**Comment by egeloen** [comment]
@jeromegamez Yep, let's do it for guzzle 3 too.

**Comment by GrahamCampbell** [comment]
> Yep, let's do it for guzzle 3 too.

:-1: Guzzle 3 is still really widely used.

**Comment by egeloen** [comment]
Yep, packagist states that guzzle 3 has been downloaded more than 4000 times today. So, it is defitively widely used, so let's keep it!

**Comment by GrahamCampbell** [comment]
For example, the current stable release of the aws sdk still uses guzzle 3. I suspect the next major version of the aws sdk will use guzzle 6 though.

**Comment by lorenzo** [comment]
:+1:
