### ISSUE TITLE
Rewrite integration tests

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#105]
Looking at travis config, integration tests are done using apache which adds unnecessary complexity to the workflow IMO.

How about packaging a small server script (written in NodeJS or more preferably using ReactPHP)? That way the whole testing workflow can be done in pure PHP (or easier in javascript than apache)

**Comment by jeromegamez** [comment]
How about using https://mockbin.com ?

**Comment by sagikazarmark** [comment]
uhm, is it an online service?

**Comment by egeloen** [comment]
Closing as we now rely on the PHP built in server which is definitively so easy to run :)
