### ISSUE TITLE
BC Break in StreamableInterface::getContents

### ISSUE THREAD

**Issue by florianv** [egeloen/ivory-http-adapter#106]
Before `StreamableInterface::getContents` would return the response body content. As of version 0.7.1 `getContents` returns an empty string even if the stream was not read:

```php
// $content is an empty string
$content = $httpAdapter->get('https://www.google.fr')->getBody()->getContents();
```

**Comment by egeloen** [comment]
What is the adapter you use?

**Comment by egeloen** [comment]
ping @florianv

**Comment by florianv** [comment]
The issue can be reproduced with `CurlHttpAdapter` or `FileGetContentsHttpAdapter`.

**Comment by egeloen** [comment]
Thanks for the feedback. I think I have spotted the issue and will provide a fix tonight :)

**Comment by egeloen** [comment]
Your issue has been fixed in the referenced PR.

**Comment by florianv** [comment]
Nice thanks!
