### ISSUE TITLE
Howto get Response Time

### ISSUE THREAD

**Issue by digitalkaoz** [egeloen/ivory-http-adapter#112]
with curl you could read it with `curl_getinfo` but howto get it into all adapters? especially when using the multi requests feature?

it tried it with the StopWatch Subscriber but had no luck as it only measure all-start and all-end.

any other possible solution?

**Comment by digitalkaoz** [comment]
event with `Timer` and `LoggerSubscriber` i dont get the correct results :/

**Comment by egeloen** [comment]
Hum, what do you expect to get as time? For now, you have two possibilities:

 * Rely on the stopwatch adapter: This one times the whole timing (requests + subscribers + ...)
 * Rely on the stopwatch subscriber: This one times the request timing (only request as it is a subscriber registers as the very first one for all kind of events).

**Comment by digitalkaoz** [comment]
i would expect the `request time` but as i said, last time i checked the stopwatch subscriber cant measure request times correctly for multi requests (i need the time of every (sub)request) as its possible with raw curl

**Comment by egeloen** [comment]
I see so the issue is only related to multi requests.

**Comment by digitalkaoz** [comment]
exactly...the attached PR fixes it (but maybe its not the best solution)

**Comment by egeloen** [comment]
This is a known limitation of the library and will not  be fixed as this repository is deprecated in favor of https://github.com/php-http Thg good fix is to upgrade following http://docs.httplug.io/en/latest/httplug/migrating/
