### ISSUE TITLE
Can't get RedirectSubscriber to work

### ISSUE THREAD

**Issue by Gremlyn** [egeloen/ivory-http-adapter#115]
Using Symfony2. I'm sure I'm doing this wrong, but I have simply registered the RedirectSubscriber in my services.yml tagged as a kernel.event_subscriber. I am attempting to access a site that 301's from http://www.example.com to http://example.com, and am using a basic CurlHttpAdapter, but I'm just getting the 301 back instead of following it.

**Comment by egeloen** [comment]
Can you copy/paste some code?

**Comment by Gremlyn** [comment]
Will do. Might take me a couple of days as I transitioned to a different project for a few days, but hope to be back on this soon.

**Comment by egeloen** [comment]
After reading your original post, I realize you maybe doing it wrong. First of all, how do you use the library (standalone or via the bundle)? If you use it as standalone be sure th event subscriber used by the library is the one used by the kernel. If you use it via the bundle, I need to rework it as it is a little be late comparing to the library...

**Comment by Gremlyn** [comment]
I'm using the stand-alone (didn't realise there was a bundle too). My service is added like this:

> ivory.redirect:
>     class: Ivory\HttpAdapter\Event\Subscriber\RedirectSubscriber
>     tags:
>        - { name: kernel.event_subscriber }

I'm using this in conjunction with fxmlrpc. I create a new CurlHttpAdapter, with a for now empty new Configuration, and pass that to the fxmlrpc Client through their included HttpAdapterTransport. Code looks like this:

> $curl = new CurlHttpAdapter(new Configuration());
> $client = new Client($website, new HttpAdapterTransport($curl));

Non-redirected sites work just fine, so it looks like I did something right, but getting the redirect to work has me stumped.

**Comment by egeloen** [comment]
Ok so you don't use the bundle. I would recommend you to use it (that will ease your use of the library) but for now, it is not up to date with the lib... If you want to use the event Symfony2 event dispatcher in the library you must use the event dispatcher http adapter (See https://github.com/egeloen/ivory-http-adapter/blob/master/doc/adapters.md#event-dispatcher)

**Comment by Gremlyn** [comment]
Ah so there is a wrapper to put around my CurlHttpAdapter that also requires the event dispatcher to be passed in? Not sure how I managed to miss that part of the docs, thanks! I'll try it out sometime soon - maybe someday I'll manage to get back to this project :\

**Comment by Gremlyn** [comment]
I switched over to the bundle and got everything configured. Once I determined I needed to require strict RFC compliance (page only accepts POST), everything worked perfectly. Thanks!!
