### ISSUE TITLE
Setting CAINFO & CAPATH

### ISSUE THREAD

**Issue by fprochazka** [egeloen/ivory-http-adapter#116]
I've just found out that travis is dying with https version of [google geocoder from willdurand/geocoder](https://github.com/geocoder-php/Geocoder), which uses this library. And there is no way to solve it currently.

> Ivory\HttpAdapter\HttpAdapterException
> An error occurred when fetching the URI "https://maps.googleapis.com/maps/api/geocode/json?address=Cejl%20486%2C%20Brno&language=cs_CZ&region=CZ" with the adapter "curl" ("GnuTLS recv error (-9): A TLS packet with unexpected length was received.").

However, disabling the verification (like #62 does) is 100% of the times wrong.
Better is to have an option to set the `CURLOPT_CAINFO` and `CURLOPT_CAPATH` with [custom certificate bundle](https://github.com/Kdyby/CurlCaBundle) (or with the custom self-signed certificate, if there is no other way).
But having the option doesn't hurt, sometimes it's just faster to test something with disabled SSL. The problem is when disabled verification gets into production :( 

Anyways, the pullrq #62 is a good skeleton, so I'm gonna wait till it's merged (unless it's not going to be merged) and I'd be happy to send a pullrq that would add the options for the custom certificates to be set.
Unless somebody will want that more than me and does it first :)

**Comment by egeloen** [comment]
:+1: Ssl verification is a must to have in production.

**Comment by egeloen** [comment]
This is a known limitation of the library and will not  be fixed as this repository is deprecated in favor of https://github.com/php-http The good fix is to upgrade following http://docs.httplug.io/en/latest/httplug/migrating/
