### ISSUE TITLE
PSR-7 issues

### ISSUE THREAD

**Issue by jenssegers** [egeloen/ivory-http-adapter#117]
There are issues with the abandoned phly/http package:

Check:

 - https://github.com/geocoder-php/Geocoder/issues/440
 - https://github.com/geocoder-php/Geocoder/issues/438

**Comment by willdurand** [comment]
ping @egeloen

**Comment by egeloen** [comment]
Sorry for the delay, geocoder-php/Geocoder#440 should be fixed with 4f35c0e49ed242ddae5c3b16b2514eaad6e8723d

For geocoder-php/Geocoder#438, it is a little bit more complex because the current guzzle 5 adapter is not compatiblae with Guzzle 6, so, I or someone will need to implement an adapter for it

**Comment by willdurand** [comment]
:+1: thanks!

**Comment by azcoppen** [comment]
#440 not fixed - see original post

**Comment by mariano** [comment]
@azcoppen @egeloen It does fix the issue, but naturally a new release has to be made. Until then you can use a little composer-fu to fool those packages that require http-adapter into thinking they DO have 0.7:

```bash
$ composer require egeloen/http-adapter "dev-master as 0.7"
```

You can then go ahead and install the latest geocoder release:

```bash
$ composer require willdurand/geocoder
```

**Comment by egeloen** [comment]
SO, here we are! I have just added Guzzle 6 support via a new adatper and also release the 0.8 version. Give me some feedback, in theory, this issue should be fixed.

**Comment by jeromegamez** [comment]
Nice one! :clap: @egeloen

**Comment by willdurand** [comment]
:+1:
