### ISSUE TITLE
[RFC] Update Socket Adapter

### ISSUE THREAD

**Issue by joelwurtz** [egeloen/ivory-http-adapter#119]
Hello,

I'm one of the maintainer of the [docker-php](https://github.com/stage1/docker-php) library, and we are currently thinking to use this library, in replacement of guzzle (v4), to support PSR7 and allow user to choose their own http lib implementation.

Docker need various functionnality in the http adapter and currently none of the existent will allow the full usage of the api, here is the functionality needed:

## TLS and Custom Certificate

The default API for a docker daemon has tls enabled and give you a certificate, so when using an http adapter we need to handle tls connection and passing a custom certificate.

## Differentiate transport and http

Docker API can be called on a unix socket file (default behavior, unix:///var/run/docker.sock). Actually all librairies parse the uri of the request as the entrypoint for the connection (like in SocketAdapter, http = tcp, and https = ssl, but these protocols are not equal and operate at different level in the network)

## Asynchronous Stream

On some api calls, Docker send a chunked response (each chunk is a json object) to implement long polling and allow to view a result in real time. However some libs does not send the response until it is complete (like zf2 see https://github.com/zendframework/zend-http/blob/master/src/Client/Adapter/Socket.php#L396).

Also the library need to send another request when another response is not fully received. But by waiting the response to be complete the client is completly blocked and this use case is not possible.

## Adapter Comparison

I briefly read all librairies implementation to see which functionnality they support:

|                 | TLS                | Transport    | Asynchronous       |
|-----------------|--------------------|--------------|--------------------|
| Buzz            | :red_circle:       | :red_circle: | :red_circle:       |
| Cake            | :white_check_mark: | :red_circle: | :red_circle:       |
| cURL            | :red_circle:       | :red_circle: | :red_circle:       |
| FileGetContents | :red_circle:       | :red_circle: | :red_circle:       |
| Fopen           | :red_circle:       | :red_circle: | :red_circle:       |
| Guzzle          | :question:         | :red_circle: | :red_circle:       |
| GuzzleHttp      | :white_check_mark: | :red_circle: | :white_check_mark: |
| HttpFul         | :white_check_mark: | :red_circle: | :red_circle:       |
| PeclHttp        | :white_check_mark: | :red_circle: | :white_check_mark: |
| React           | :red_circle:       | :red_circle: | :white_check_mark: |
| Socket          | :red_circle:       | :red_circle: | :red_circle:       |
| Zend1           | :white_check_mark: | :red_circle: | :red_circle:       |
| Zend2           | :white_check_mark: | :red_circle: | :red_circle:       |

## Updating Socket Adapter

I think implementing these functionnality into the SocketAdapter does not require a huge amount of work (some work can be take from our current adapter for guzzle 4 in docker-php library : https://github.com/stage1/docker-php/blob/master/src/Docker/Http/Adapter/DockerAdapter.php) And i will be glad to do this PR. I have however some questions before beginning this work.

1. Is this something you want to support in your library ?

2. If not i would like to extract logic from current SocketAdapter into another class for reusability (like creating the request string from the request object)

3. If yes, how do you prefer to pass configuration for this functionnality (transport, certificate, tls / ssl protocol to use) ? This can be done in the Configuration object, however too few librairies can use those options and this may not be very useful.

**Comment by sagikazarmark** [comment]
This adapter package is currently being migrated to [php-http](https://github.com/php-http). It is not stable yet, but the API is close to an alpha release. Maybe it worth a check.

About the socket adapter changes: this is something that I would also like to see.

About point three: the current Configuration object is not quite permissive. In the new adapter package this will be replaced by an options array.

**Comment by joelwurtz** [comment]
I have seen it, but i wasn't aware of the advancement, once the alpha is out you can maybe ping me and i will take a look for implementing this package : https://github.com/php-http/socket-adapter

**Comment by sagikazarmark** [comment]
Will do.

**Comment by joelwurtz** [comment]
Hey, any news for the alpha ? Is there something i can do to help in order to have a first release ?

**Comment by sagikazarmark** [comment]
Currently I am trying to contact @egeloen about the future of the project. I think there is not much left from getting to an alpha state. If you take a look at the terminology and exception branches in the adapter: that's the way it is going to work.

**Comment by joelwurtz** [comment]
I see that, no problem i will begin work on the socket adapter tomorrow based on the current terminology branch (even if it change it should not be so drastic) can you init the socket-adapter project with a file so i can make a fork ?

**Comment by sagikazarmark** [comment]
As I can see you've already started working in a custom repository. I would say you are free to work there, @dbu is also working on the Symfony Bundle in his custom namespace. When you are ready, we can move it here. Also, I think adapter name will probably change to something like client or a fantasy name. So even the naming is not final.

**Comment by dbu** [comment]
for reference: https://github.com/dbu/HttpClientBundle/pulls

**Comment by egeloen** [comment]
This is a known limitation of the library and will not  be fixed as this repository is deprecated in favor of https://github.com/php-http The good fix is to upgrade following http://docs.httplug.io/en/latest/httplug/migrating/
