### ISSUE TITLE
Composer cannot find matching package 

### ISSUE THREAD

**Issue by lukepolo** [egeloen/ivory-http-adapter#124]
willdurand/geocoder v3.3.0 requires egeloen/http-adapter ~0.8 -> no matching package found.
willdurand/geocoder 3.3.x-dev requires egeloen/http-adapter ~0.8 -> no matching package found.
Installation request for willdurand/geocoder ^3.3 -> satisfiable by willdurand/geocoder[3.3.x-dev, v3.3.0].

**Comment by xabbuh** [comment]
How does your `composer.json` file look like and which version of Composer do you use?

**Comment by lukepolo** [comment]
It was a willdurand/geocoder issue .Sorry!
