### ISSUE TITLE
Add new http adapters

### ISSUE THREAD

**Issue by egeloen** [egeloen/ivory-http-adapter#33]
In this post, you can propose an http client library in order to add its support :) For now, if you would like to contribute, the following http adapters need to be implemented:

Done:

 * [x] Buzz
 * [x] Cake
 * [x] cURL
 * [x] FileGetContents
 * [x] Fopen
 * [x] Guzzle
 * [x] GuzzleHttp
 * [x] Httpful
 * [x] PECL HTTP
 * [x] React
 * [x] Requests (rmccue)
 * [x] Socket
 * [x] Zend1
 * [x] Zend2

**Comment by sagikazarmark** [comment]
Imported from awesome php repo:

https://github.com/rmccue/Requests

Also, this library itself should be listed in awesome php packages.

**Comment by egeloen** [comment]
Closing as this repository is deprecated in favor of https://github.com/php-http
