### ISSUE TITLE
Add new subscribers

### ISSUE THREAD

**Issue by egeloen** [egeloen/ivory-http-adapter#60]
In this post, you can propose a subscriber in order to add its support :) For now, if you would like to contribute, the following subscribers need to be implemented:

Done:

 * [x] Basic authentication
 * [x] Cache
 * [x] Cookie
 * [x] History
 * [x] Logger
 * [x] Redirect
 * [x] Retry
 * [x] Status
 * [x] Stopwatch
 * [x] Tape recorder (https://github.com/kreait/tape-recorder-subscriber)

**Comment by sagikazarmark** [comment]
For cache I suggest you taking a look at [Stash](http://stashphp.com)

**Comment by egeloen** [comment]
Closing as this repository is deprecated in favor of https://github.com/php-http
