### ISSUE TITLE
HTTP adapter does not have ->getEventDispatcher() method

### ISSUE THREAD

**Issue by RobinvdVleuten** [egeloen/ivory-http-adapter#64]
Hi there,

If you read the cookbook about events, the example shows that you can call `getEventDispatcher()` on a `$httpAdapter` instance. But I get an error thrown about an undefined method call. I can call this method on a `$configuration` instance instead.

Cheers,
Robin

**Comment by egeloen** [comment]
This is a documentation issue rather than a code issue. Closing as we will refactor the event dispatching into a decorator.
