### ISSUE TITLE
Update to PSR7 0.6

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#68]
The new PSR7 interface package has been tagged. Complete rewrite....again.

**Comment by egeloen** [comment]
Yeah, I have seen it https://twitter.com/egeloen/status/560031138568478721 I will work on it this week-end!

**Comment by kasperg** [comment]
Thank you for sharing Ivory HTTP Adapter.

I do not mean to pile on but we are now at PSR-7 0.8. I guess that that should be the target now.

**Comment by egeloen** [comment]
Closing in favor of #74
