### ISSUE TITLE
Stop too long/too big requests

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#75]
Is it possible to stop too long requests? I don't mean requests without response, but a request which is getting a response for a long time (eg. because of slow connection).

The other thing is having a possible limitation on downloaded content size. A possible solution would be to stop downloading based on header's Content-Length header.

Any thoughts?

**Comment by sagikazarmark** [comment]
Both would serve having long running, memory consuming requests stopped if necessary.

**Comment by egeloen** [comment]
I don't think it would be possible. The biggest problem is to be able to archive it for all adapters... Maybe, the best we can do is to move some configuration option to the request level. Then, we would be able to configure different timeout for each request in a all context (serial & parallel).

But in any case, it would require to decore headers as soon as they are received which seems not implementable for all adapters and would require a lot of change in the code for adapters where it would be possible.

**Comment by sagikazarmark** [comment]
I am thinking about doing two requests: a HEAD and a "normal" one. Could it work?

**Comment by egeloen** [comment]
Yeah, in theory it should work as the headers would be returned without the body and so, you can rely on the `Content-Length` header.

**Comment by egeloen** [comment]
@sagikazarmark Does sending an `HEAD` request fixes your issue? IMO, I will not decode headers as soon as they are received as this will not be implementable for all adapters.

**Comment by jeromegamez** [comment]
Sending a HEAD request *is* the way to go and meant for this use case. If every request has to be checked, I think an Event Listener to the PRE_SEND event would be the easiest solution.

**Comment by egeloen** [comment]
Yep sounds like a good candidate for a subscriber.

**Comment by sagikazarmark** [comment]
It depends on the webserver. By definition it should be the way to go.
However I can't say it is an ultimate solution hence some insane webserver
implementations. Also, CDNs might not behave as expected.

**Comment by egeloen** [comment]
After thinking and thinking about it, I can't find a solution which will work for all adapters... So, IMO, this issue is a nofix one :s Using the `HEAD` request is probably the better option you have.
