### ISSUE TITLE
Mutability in subscribers and related objects

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#84]
Moving from #82:

All of the mentioned objects are mutable and I wonder if they really should be. Once a subscriber is passed to the event dispatcher it really shouldn't be changed. And I can hardly think of a use case where there is a mutator layer between the subscriber and the dispatcher. This is all true for the related objects (BasicAuth etc.)

Speaking of related objects: are they really necessary? I mean, I can't think of a use case, do you have any? For example in case of a simple basic auth it is rather an overkill, since we are talking about two simple data and a mutator logic which is probably the same in every possible implementation.

**Comment by egeloen** [comment]
The mutability in the event listeners/subscribers are not needed. So, I agree for removing them. For the related objects, I have designed it this way in order to allows to use them in an other event dispatcher library without having to duplicate the whole logic. So, for this part, I'm for keeping them.

**Comment by sagikazarmark** [comment]
OK. May I open a separate PR from #85, or I can send the two in one (as event dispatching improvement)?

**Comment by egeloen** [comment]
Less PR to review, better it is :) And as you pointed out, everything is related to event dispatching, so :+1: for putting everything in a single PR.

**Comment by sagikazarmark** [comment]
Great, thanks. Will send it in a few days.
