### ISSUE TITLE
Idea about events

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#85]
I think it is getting more and more common to treat events as something happened in the *past* (eg. OrderSent). Pre/Post prefixed events doesn't really fit into this. What do you think about this?

Possible event transitions:
PreSend => RequestCreated
PostSend => RequestSent
Exception => RequestErrored

(and their multi variants)

It's easier to fit into the flow of application using the logic "something happened, so do something else".

**Comment by sagikazarmark** [comment]
@egeloen ping

**Comment by egeloen** [comment]
Sorry for the delay! I'm at the same time :+1:/:-1: :) Basically, I would say it does not matter, I can understand both (for example, `PreSend` and `RequestCreated` definitively reflect the same concept but does not use the same referential). As you have understood, I have designed everything about the send verb whereas you would design the event around different concept (create and send).

Let's see what others think.

**Comment by sagikazarmark** [comment]
Actually the concept I suggest is not about the exact word used.

In event-driven design listeners act when an event occurs, which means that any logic that a listener executes is *after* the event. From a listener point of view the occurrence of the event is in the past. So whichever word is used, following this logic events are in the past, thus a name reflecting that should be used.

But it is probably a personal preference. The reason I opened this issue is that you mentioned you might want to move event logic into a separate package which might be the perfect time for a change like this.

**Comment by egeloen** [comment]
Let's go for it!

**Comment by sagikazarmark** [comment]
I am not sure how I should rename the exception event.

Some ideas:

- Request failed
- Error occured
- Failed
- Errored

My preference is request failed, however it is strongly tied to the fact that exceptions are all produced by a faulty request. Is that true?

**Comment by sagikazarmark** [comment]
I found that you have a very detailed docblock style, but I think we could narrow it down a bit:

```
    /**
     * On multi request created event.
     *
     * @param \Ivory\HttpAdapter\Event\MultiRequestCreatedEvent $event The multi request created event.
     */
```

into this:

```
    /**
     * @param \Ivory\HttpAdapter\Event\MultiRequestCreatedEvent $event
     */
```

or even:

```
    /**
     * @param MultiRequestCreatedEvent $event
     */
```

since the class is imported into the current namespace.

What do you think?

**Comment by egeloen** [comment]
I like your first proposal (`RequestErrored`), so let's go for it. About the docblock, it is on my TODO list. I will convert all of them into short class name and add a use statement everywhere. So, you can start using the short one.

**Comment by egeloen** [comment]
And yes, if an exception is thrown it is always related to a bad request or something which goes wrong with the request such as timeout, connectivity issue, etc

**Comment by sagikazarmark** [comment]
Is it still your plan to split the package and put events into a separate one?

Because I can do that for you of you would like.

What is needed for it:

- Agree on a name (ivory-http-symfony-event?)
- Discuss where to put the event-dispatcher-independent files (BasicAuth, etc) They could remain in the main package or go into a third one.
- Where to put docs: in the separated packages or just link the events to the separated packages.

**Comment by egeloen** [comment]
Yes, I will split the package but let fix the related issue first :)
