### ISSUE TITLE
HTTP Adapter trait closure typehing

### ISSUE THREAD

**Issue by sagikazarmark** [egeloen/ivory-http-adapter#92]
Shouldn't [this](https://github.com/egeloen/ivory-http-adapter/blob/master/src/HttpAdapterTrait.php#L161) type hint be `Psr\Http\Message\ResponseInterface`.

Actually I am only asking it because testing.

**Comment by egeloen** [comment]
Yes, we can typehint againt the psr one but it will not change anything are we are in internal code here. What is the problem with this typehint?
