### ISSUE TITLE
0.7.1 release

### ISSUE THREAD

**Issue by jeromegamez** [egeloen/ivory-http-adapter#94]
If possible, could you release a 0.7.1 release from the current master? I would like to use 0.7.* in another project, but this is currently not possible due to the `"phly/http": "dev-header-case-sensitivity as 0.11.x-dev"` dependency which has been fixed in 1e174e7.

Perhaps it would even be sufficient to cherry pick this commit for a 0.7.1 and bump the current dev-master to 0.7.2

Cheers
:octocat: Jérôme

**Comment by egeloen** [comment]
Done!
